name: pull from hatenablog

on:
  workflow_dispatch:

jobs:
  pull:
    uses: ./.github/workflows/_pull.yaml # fix
    with:
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
